title: ISMRM - Latin American Chapter

plugins:
  - jekyll-sitemap
  - jekyll/tagging

# or different production / staging locations.
  - ../component-library

exclude:
  - postcss.config.js
  - node_modules

include:
  - _cloudcannon

collections_dir: 'collections'

collections:
  pages:
    output: true
    permalink: /:title/
  projects:
    output: true
    permalink: /project/:slug
  previous_projects:
    output: true
    permalink: /previous-project/:slug
  testimonials:
    output: false
  posts:
    output: true
    permalink: /blog/:slug

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      type: pages
      path: _pages/index.html
    values:
      permalink: /
  - scope:
      type: projects
    values:
      layout: project
  - scope:
      type: previous_projects
    values:
      layout: project
  - scope:
      type: posts
    values:
      layout: post

# Tags
tag_page_dir: tag
tag_page_layout: tag_page
tag_permalink_style: /:title
