title: ISMRM - Latin American Chapter
description: La membresía al capítulo está abierta a profesionales interesados en la resonancia magnética en medicina y biología, sin importar su nacionalidad, que residan en América Latina o sean ciudadanos latinoamericanos viviendo en otro país.| Membership to the chapter is open to professionals interested in magnetic resonance in medicine and biology, regardless of nationality, who reside in Latin America or are Latin American citizens living in another country.
social_media_share_image: /uploads/Logo_ismrm.png
disqus-identifier:
google-analytics: