name: Event Registration
description: Submit a workshop, webinar, or meeting
title: "Event: [Event Name]"
labels: ["new-event"]
body:
  - type: input
    id: organizer
    attributes:
      label: Who is inviting?
      placeholder: e.g., ISMRM-LATAM Executive Committee / University of Chile
    validations:
      required: true
  - type: dropdown
    id: category
    attributes:
      label: Event Type
      options:
        - Webinar
        - Workshop
        - Conference
        - Social Event
        - Chapter Meeting
    validations:
      required: true
  - type: input
    id: event-date
    attributes:
      label: When will it happen?
      placeholder: "YYYY-MM-DD"
      description: "Format: YYYY-MM-DD (e.g., 2026-05-15)"
    validations:
      required: true
  - type: dropdown
    id: modality
    attributes:
      label: Modality
      options:
        - Virtual
        - In-person
        - Hybrid
    validations:
      required: true
  - type: input
    id: location
    attributes:
      label: Where will it happen?
      placeholder: "e.g., Zoom / Santiago, Chile / Honolulu, HI"
    validations:
      required: true
  - type: input
    id: registration-link
    attributes:
      label: Registration or Info Link
      placeholder: "https://..."
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: "Provide a brief overview of the event. Keep in mind that you need to use Markdown formatting for line breaks, lists, etc. If you wish to include an image, we advice you to upload it to an image hosting service (e.g., Imgur) and include the URL here using Markdown syntax: ![Alt Text](Image URL). If you want to upload the image to GitHub, you can drag and drop the image into the comment box after submitting the issue, and then copy the generated Markdown link back into this description field."
    validations:
      required: true